# Generated by Django 5.2.10 on 2026-01-22 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_act', models.CharField(max_length=20, unique=True)),
                ('nom_act', models.CharField(max_length=100)),
                ('tarif_mensuel', models.FloatField()),
                ('capacite', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='activities/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_telephone', message='Le numéro de téléphone doit contenir exactement 8 chiffres.', regex='^\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.activity')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member')),
            ],
            options={
                'unique_together': {('membre', 'activite')},
            },
        ),
    ]
