# Generated by Django 6.0.1 on 2026-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
