# Generated by Django 6.0.1 on 2026-01-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_member_actif_member_date_inscription_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('3_MONTHS', '3 Mois'), ('6_MONTHS', '6 Mois'), ('ANNUAL', 'Annuel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='club.member')),
            ],
        ),
    ]
