# Generated by Django 6.0.1 on 2026-01-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='club.activity')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('activite', 'date', 'heure_debut')},
            },
        ),
    ]
